# Site settings
title: Fred Cook
description: Fred Cook's website
baseurl: "fuverdred.gitub.io"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Fred Cook
user_description: I am a finishing physics PhD student looking to convert to software development. My PhD is largely experimental, focusing on developing experimental methods for observing ice nucleation. However, I also developed Python experience through data analysis and modelling, as well as various personal projects.
user_title: Software Developer
email: fred@fredcook.co.uk
github_username:  fuverdred

exclude: ['package.json', 'src' , 'node_modules']
