# Site Settings
locale                   : "en-UK"
title                    : "Fred Cook"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Fred Cook"
author                   : "Fred Cook"
description              : "Somewhere to host my CV"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
